import { Geist, Geist_Mono } from "next/font/google";
import "../styles/css/globals.css";
import styles from "../styles/scss/_globals.module.scss";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import ClientProviders from "../components/users/ClientProviders.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.body}`}>
        <ClientProviders>
          <Header />
          <main className={styles.main}>{children}</main>
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}

